### ISSUE TITLE
[BUG] Multi-determinant example is not working

### ISSUE THREAD

**Issue by q-mat-beu** [JoonhoLee-Group/ipie#265]
**Describe the bug**
I experimented with ipie and pyscf to run AFQMC with MCSCF wavefunction and ran into an error. The same error occurs when following the steps in the example 02 folder. The stacktrace is:

```
Traceback (most recent call last):
  File "/Users/matthiasbeuerle/ipie/bin/ipie", line 82, in <module>
    main(sys.argv[1])
  File "/Users/matthiasbeuerle/ipie/bin/ipie", line 77, in main
    afqmc.run(verbose=True)
  File "/Users/matthiasbeuerle/ipie/ipie/qmc/afqmc.py", line 393, in run
    self.setup_estimators(estimator_filename, additional_estimators=additional_estimators)
  File "/Users/matthiasbeuerle/ipie/ipie/qmc/afqmc.py", line 329, in setup_estimators
    self.estimators.compute_estimators(
  File "/Users/matthiasbeuerle/ipie/ipie/estimators/handler.py", line 204, in compute_estimators
    e.compute_estimator(system, walker_batch, hamiltonian, trial)
  File "/Users/matthiasbeuerle/ipie/ipie/estimators/energy.py", line 137, in compute_estimator
    energy = local_energy(system, hamiltonian, walkers, trial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthiasbeuerle/miniconda3/envs/lib/python3.11/site-packages/plum/function.py", line 399, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthiasbeuerle/ipie/ipie/estimators/energy.py", line 90, in local_energy
    return local_energy_multi_det_trial_wicks_batch_opt(system, hamiltonian, walkers, trial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthiasbeuerle/pie/ipie/estimators/local_energy_wicks.py", line 945, in local_energy_multi_det_trial_wicks_batch_opt
    det_sizes_a = max([len(trial.cre_ex_a[i]) * i * i for i in range(1, trial.max_excite + 1)])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**To Reproduce**
Execute instructions in `ipie/examples/02-multi_determinant/README.rst`

**Expected behavior**
afqmc completes without an error

**Other information:**
 - Latest commit: ac51a882a9b2f9fccc210347e98e33956b08a97a
 - OS: macOS Ventura 13.6

**Comment by jiangtong1000** [comment]
Hi Matthias, @q-mat-beu ,
You should specify the number of dets used for trial energy calculation and propagation, as I mentioned in #266

**Comment by q-mat-beu** [comment]
Hi @jiangtong1000 , works now, thanks!
